### ISSUE TITLE
'ListIndex' object has no attribute 'query'

### ISSUE THREAD

**Issue by CesareSwift** [onlyphantom/llm-python#12]
when using the following code to create index, I got errors such as 'ListIndex' object has no attribute 'query' and AttributeError: 'ListIndex' object has no attribute 'save_to_disk'. 
```
@timeit()
def create_index():
    print("Creating index")
    # Wrapper around an LLMChain from Langchaim
    llm = LLMPredictor(llm=LocalOPT())
    # Service Context: a container for your llamaindex index and query
    # https://gpt-index.readthedocs.io/en/latest/reference/service_context.html
    service_context = ServiceContext.from_defaults(
        llm_predictor=llm, prompt_helper=prompt_helper
    )
    docs = SimpleDirectoryReader("news").load_data()
    index = GPTListIndex.from_documents(docs, service_context=service_context)
    print("Done creating index", index)
    return index
  
```
File "demo9.py", line 101, in execute_query
    response = index.query(
AttributeError: 'ListIndex' object has no attribute 'query'

**Comment by onlyphantom** [comment]
You may have to install from requirements.txt to pin the version of langchain and llamaindex to 0.0.209 and 0.6.31. 

Both are relatively young projects so expect lots of breaking changes every few weeks!
