### ISSUE TITLE
pip install -r requirements.txt has some dependency/version issues

### ISSUE THREAD

**Issue by leximAI** [onlyphantom/llm-python#2]
I have seen this error with other projects (not yours) when the python version was in mismatch. I currently have 3.9.6 (errors were reported with 3.11.x)...so not sure what may be going on here. 

----------

Collecting uvloop==0.17.0 (from -r requirements.txt (line 112))
  Using cached uvloop-0.17.0.tar.gz (2.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\patbh\AppData\Local\Temp\pip-install-qa53rwky\uvloop_94d9148e502f4a8689747849ae1f0a57\setup.py", line 8, in <module>
          raise RuntimeError('uvloop does not support Windows at the moment')
      RuntimeError: uvloop does not support Windows at the moment
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by onlyphantom** [comment]
just to get to the bottom of this,

> raise RuntimeError('uvloop does not support Windows at the moment')

A later version of `uvloop` itself works with Windows, but not the `0.17.0` version? Why do you think it was a python version mismatch issue? 

I need some help troubleshooting this as I'm using Linux as my daily driver, but if the fix is as simple as bumping up `uvloop` then it'd be easy to review and / or merge.

**Comment by leximAI** [comment]
Thanks for the response. Let me try a few things and let you know. The reason why I suggested it could be the python version is that in the past that was the case for other projects that I cloned and ran from GH.

**Comment by leximAI** [comment]
Unless I rebuild a whole bunch of packages, I will not be able to use the code on Windows. It will be nice if you can release a Windows working version as well. Thank you.

**Comment by onlyphantom** [comment]
Solved in the latest commit of #7

**Comment by leximAI** [comment]
Thank you.
