### ISSUE TITLE
Request for License Definition

### ISSUE THREAD

**Issue by yokingly** [onlyphantom/llm-python#5]
Hello,

I love all of your Youtube content upon reviewing your repo I've noticed that this repository currently doesn't have a license.

It would be very helpful if you could add a license to this repository. If you're unsure about which license to choose, GitHub has a guide [here](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository).

Thank you

**Comment by onlyphantom** [comment]
Good tip, will be adding by end of day! Thank you!
